### PR TITLE
Allow usage of ArcOS on Firefox.

### PR DESCRIPTION
**Pull request by ghost**
Allows Firefox users to access ArcOS

> [!NOTE]
> The formatting for some files was changed due to my prettier configuration.

image

### CODE REVIEW

**Comment by IzKuipers** [comment]
how come the 3 spaces instead of 2

**Comment by ghost** [comment]
> @IzKuipers: how come the 3 spaces instead of 2

You didn't read my note....

> [!NOTE]
> The formatting for some files was changed due to my prettier configuration.

**Comment by eversiege** [comment]
> how come the 3 spaces instead of 2

Riveting information

**Comment by ghost** [comment]
> > how come the 3 spaces instead of 2
> 
> @eversiege: Riveting information

He didn't even read the thing, It clearly said "The formatting for some files was changed due to my prettier configuration."

**Review by IzKuipers — CHANGES_REQUESTED** [review]
Change the formatting back to the way it was (double quotes, 2 spaces instead of 3), and drop the support notification entirely

**Comment by ghost** [comment]
> @IzKuipers: Change the formatting back to the way it was (double quotes, 2 spaces instead of 3), and drop the support notification entirely

Alright

**Comment by ghost** [comment]
@IzKuipers you didnt change the `package.json` version for a while (its `5.0.9` atm)

**Comment by IzKuipers** [comment]
> @IzKuipers you didnt change the `package.json` version for a while (its `5.0.9` atm)

doesn't matter as nothing listens to that property

**Comment by ghost** [comment]
> you didnt change the `package.json` version for a while (its `5.0.9` atm)
> 
> @IzKuipers: doesn't matter as nothing listens to that property

alright

**Comment by ghost** [comment]
@IzKuipers Is it good now?

**Pull request merged**
